station = ["EX_Djerdap.vbs"; "EX_LaEska.vbs"; "EX_Nuoja.vbs"; ...
           "EX_Plyvna.vbs"; "EX_PuntaNegra.vbs"; "EX_SaoJoao.vbs"; ...
           "EX_Saratovskya.vbs"; "EX_Sayany.vbs"; "EX_Taini.vbs"; ...
           "EX_Vozhsky.vbs"; "EX_Votkinsckaya.vbs"; "EX_Baksan.vbs"];
filename = table(station);
idx = isfile(filename.station);
exfile = filename(idx, :);
setPath(exfile.station);       